# Generated by Django 4.2.7 on 2024-03-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(upload_to='invoices')),
            ],
        ),
        migrations.CreateModel(
            name='KS61',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registered_Business_Address', models.JSONField(blank=True, null=True)),
                ('Telephone', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Company_Number', models.CharField(max_length=20)),
                ('Vat_Number', models.CharField(max_length=20)),
                ('Trading_Address', models.JSONField()),
                ('Business_Name', models.CharField(max_length=50)),
                ('Account_Terms', models.CharField(max_length=20)),
                ('Invoice_Date', models.CharField(max_length=20)),
                ('Invoice_Number', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('Authorisation_Number', models.CharField(max_length=20)),
                ('Make', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Registration', models.JSONField(blank=True, null=True)),
                ('Description_of_Work', models.JSONField(blank=True, null=True)),
                ('Price', models.JSONField(blank=True, null=True)),
                ('Net_Total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Vat_at_20_Percent', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Invoice_Total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Total_Payable', models.CharField(max_length=100)),
                ('Payment_Due', models.CharField(max_length=100)),
                ('Customer_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ks61',
            },
        ),
    ]
