# Generated by Django 4.2.7 on 2024-03-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_app', '0002_invoices_ks61'),
    ]

    operations = [
        migrations.AddField(
            model_name='ks61',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
