# Generated by Django 4.2.7 on 2024-03-23 22:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dg_app', '0009_customuser_eemail_customuser_epassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ks61',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dg_app.invoices'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 23), editable=False),
        ),
        migrations.AlterField(
            model_name='ks61',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 3, 23), editable=False),
        ),
    ]
