# Generated by Django 4.2.7 on 2024-03-23 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_app', '0010_ks61_file_alter_invoices_date_alter_ks61_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ks61',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 3, 23)),
        ),
    ]
