# Generated by Django 4.2.7 on 2024-04-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_app', '0015_alter_invoices_date_alter_invoices_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
